package consts

var QUERY_DEPARTAMENTO = `SELECT C_CODIGO FROM VAD10..MA_DEPARTAMENTOS`

var QUERY_GRUPO = `SELECT C_CODIGO FROM VAD10..MA_GRUPOS`

var QUERY_SUBGRUPO = `SELECT C_CODIGO FROM VAD10..MA_SUBGRUPOS`
